from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from pprint import pformat
import re
from typing import Any, Mapping


_DETECTOR_ID_PATTERN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*$")


@dataclass(frozen=True)
class DetectorExportNames:
    detector_id: str
    module_name: str
    class_name: str
    detector_name: str
    defect_type: str
    bundle_name: str


@dataclass(frozen=True)
class DetectorExportResult:
    bundle_dir: Path
    detector_path: Path
    registration_guide_path: Path
    names: DetectorExportNames


class DetectorBundleExporter:
    """Render a tuned CPU reference as a registerable VisionFlow detector bundle."""

    GUIDE_FILENAME = "REGISTER_DETECTOR.md"

    def names_for(self, detector_id: str) -> DetectorExportNames:
        normalized_id = str(detector_id).strip()
        if not _DETECTOR_ID_PATTERN.fullmatch(normalized_id):
            raise ValueError(
                "Detector ID 只能使用英文字母、數字、句點、底線與連字號，"
                "而且第一個字元必須是英文字母或數字。"
            )
        words = [part for part in re.split(r"[^A-Za-z0-9]+", normalized_id) if part]
        slug = "_".join(part.lower() for part in words)
        class_suffix = "".join(part.capitalize() for part in words)
        module_name = f"detector_{slug}"
        return DetectorExportNames(
            detector_id=normalized_id,
            module_name=module_name,
            class_name=f"Detector{class_suffix}",
            detector_name=f"traditional_cv_{slug}",
            defect_type=f"{slug}_traditional_cv_ng",
            bundle_name=f"{module_name}_bundle",
        )

    def export(
        self,
        parent_dir: str | Path,
        *,
        detector_id: str,
        display_name: str,
        params: Mapping[str, Any],
    ) -> DetectorExportResult:
        names = self.names_for(detector_id)
        resolved_display_name = str(display_name).strip()
        if not resolved_display_name:
            raise ValueError("Detector 顯示名稱不可為空白。")
        snapshot = self._snapshot_params(params)

        parent = Path(parent_dir)
        parent.mkdir(parents=True, exist_ok=True)
        bundle_dir = parent / names.bundle_name
        if bundle_dir.exists():
            raise FileExistsError(f"匯出資料夾已存在：{bundle_dir}")
        bundle_dir.mkdir()

        detector_path = bundle_dir / f"{names.module_name}.py"
        guide_path = bundle_dir / self.GUIDE_FILENAME
        detector_path.write_text(
            self.render_detector(names, resolved_display_name, snapshot),
            encoding="utf-8",
        )
        guide_path.write_text(
            self.render_registration_guide(names, resolved_display_name),
            encoding="utf-8",
        )
        return DetectorExportResult(
            bundle_dir=bundle_dir,
            detector_path=detector_path,
            registration_guide_path=guide_path,
            names=names,
        )

    @staticmethod
    def _snapshot_params(params: Mapping[str, Any]) -> dict[str, Any]:
        if not isinstance(params, Mapping):
            raise TypeError("Detector 參數必須是 mapping。")
        snapshot: dict[str, Any] = {}
        for key, value in params.items():
            snapshot[str(key)] = list(value) if isinstance(value, (list, tuple)) else value
        return snapshot

    @staticmethod
    def render_detector(
        names: DetectorExportNames,
        display_name: str,
        params: Mapping[str, Any],
    ) -> str:
        params_literal = pformat(dict(params), width=100, sort_dicts=False)
        return f'''from __future__ import annotations

"""Generated by VisionFlow Traditional CV Tuning Tool.

The tuned values are intentionally frozen. Re-export this file when the processing
contract changes. This detector uses the OpenCV CPU reference path.
"""

from types import MappingProxyType

from contour_preprocess_tool.engine import ContourProcessingEngine
from detectors.base_detector import BaseDetector


class {names.class_name}(BaseDetector):
    detector_id = {names.detector_id!r}
    detector_name = {names.detector_name!r}
    display_name = {display_name!r}

    # Parameters are frozen into the generated detector, so Recipe Designer has
    # no editable fields for this class. Tune again in the standalone tool and
    # re-export when these values need to change.
    default_params = {{}}
    PARAM_SPEC = {{}}
    TUNING_PARAMS = MappingProxyType({params_literal})

    def __init__(
        self,
        display_name=None,
        params=None,
        use_gpu=False,
        gpu_runtime=None,
        ai_session_manager=None,
    ):
        if params:
            raise ValueError(
                "此 Detector 的調參值已在匯出時凍結；請回到調參工具修改並重新匯出。"
            )
        self._gpu_was_requested = bool(use_gpu)
        super().__init__(
            display_name=display_name,
            params=None,
            use_gpu=False,
            gpu_runtime=None,
            ai_session_manager=ai_session_manager,
        )

    def preprocess(self, image):
        return image

    def detect(self, image) -> list[dict]:
        with self.measure_detection_stage("tuned_cpu_reference"):
            output = ContourProcessingEngine().analyze(image, self.TUNING_PARAMS)
        self._record_debug_image("generated_tuned_mask", output.mask)
        return [
            {{
                "type": {names.defect_type!r},
                "bbox_local": list(item["bbox"]),
                "area": float(item["area"]),
                "confidence": 1.0,
                "metadata": {{
                    "shape": item["shape"],
                    "generated_from": "visionflow-traditional-cv-tuning/v1",
                    "recipe_steps": list(output.stats["recipe_steps"]),
                    "threshold_method": self.TUNING_PARAMS["threshold_method"],
                    "retrieval_mode": self.TUNING_PARAMS["retrieval_mode"],
                }},
            }}
            for item in output.stats["detections"]
        ]

    def run(self, image, device_roi=None, preprocess_cache=None) -> dict:
        result = super().run(
            image,
            device_roi=device_roi,
            preprocess_cache=preprocess_cache,
        )
        result["execution"]["gpu_requested"] = self._gpu_was_requested
        if self._gpu_was_requested:
            result["execution"]["fallback_reason"] = (
                "調參工具匯出的 Detector 固定使用 OpenCV CPU reference；"
                "完成共用 PreprocessPlan 與 CPU/GPU 等價驗證前不可啟用 CUDA。"
            )
        return result
'''

    @staticmethod
    def render_registration_guide(
        names: DetectorExportNames, display_name: str
    ) -> str:
        return f'''# 註冊 `{names.detector_id}` Detector

這個 bundle 由 VisionFlow Traditional CV Tuning Tool 產生，包含已凍結目前調參結果的 CPU Detector。

## 1. 複製 Detector

把 `{names.module_name}.py` 複製到專案的 `detectors/`。

## 2. 加入 DetectorManager

編輯 `core/detector_manager.py`，在 import 區加入：

```python
from detectors.{names.module_name} import {names.class_name}
```

在 `DetectorManager.__init__()` 的 `self._registry` 加入：

```python
{names.class_name}.detector_id: {names.class_name},
```

## 3. 加入繁中顯示名稱

編輯 `gui/detector_labels.py`，在 `DETECTOR_ZH` 加入：

```python
{names.detector_id!r}: {display_name!r},
```

## 4. 加入 Recipe

在 Recipe 的 `detectors` 區段加入；這個匯出版本固定走 CPU，因此 `use_gpu` 必須保持 `false`：

```yaml
detectors:
  "{names.detector_id}":
    enabled: true
    use_gpu: false
    display_name: "{display_name}"
    params: {{}}
```

若 `decision.important_detectors` 有列舉必要 Detector，也要加入 `"{names.detector_id}"`。

## 5. 驗證後再投入使用

1. 以同一張原始 tile/ROI 比較調參工具與新 Detector 的 PASS/NG、defect 數、bbox、area 與順序。
2. 新增 DetectorManager 註冊與 Recipe round-trip 測試。
3. 執行 repository 規定的完整 unit tests、compileall、CUDA preflight、GUI smoke 與 `git diff --check`。
4. 目前產生的是 OpenCV CPU reference。若要支援 GPU，需另行遷移成共用 immutable `PreprocessPlan`，完成 fallback 與 CPU/GPU 等價測試後才能把 `use_gpu` 改為 `true`。

調參值已寫在 `{names.module_name}.py` 的 `TUNING_PARAMS`。請回到調參工具修改後重新匯出，不要只改部分值而失去對照依據。
'''
